---
- name: Define phpmyadmin_config_file.
  set_fact:
    phpmyadmin_config_file: "{{ phpmyadmin_config_file }}"
  when: phpmyadmin_config_file is not defined

- name: Add default username and password for MySQL connection.
  lineinfile: >
    dest={{ phpmyadmin_config_file }}
    state=present
    regexp="^.+\['{{ item.key }}'\].+$"
    line="$cfg['Servers'][$i]['{{ item.key }}'] = '{{ item.value }}';"
    insertbefore="^\?>"
    mode=0644
  with_items:
    - key: host
      value: "{{ phpmyadmin_mysql_host }}"
    - key: port
      value: "{{ phpmyadmin_mysql_port }}"
    - key: socket
      value: "{{ phpmyadmin_mysql_socket }}"
    - key: connect_type
      value: "{{ phpmyadmin_mysql_connect_type }}"
    - key: user
      value: "{{ phpmyadmin_mysql_user }}"
    - key: password
      value: "{{ phpmyadmin_mysql_password }}"

- name: Ensure phpMyAdmin is installed.
  apt:
    name: phpmyadmin
    state: present
  notify: apache_restart

- name: Ensure phpMyAdmin config file is included in Apache config.
  lineinfile:
    dest: /etc/apache2/apache2.conf
    state: present
    regexp: "^Include.+phpmyadmin.+$"
    line: "Include /etc/phpmyadmin/apache.conf"
    insertafter: "EOF"
    mode: 0644
  notify: apache_restart